name: Lighthouse CI

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering
  push:
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          yarn add global @lhci/cli@0.12.0
          yarn add dotenv

      - name: run lhci
        run: |
          yarn lhci

      - name: Create .env file from GitHub secrets
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "TG_ALERT_CHANEL_ID=${{ secrets.TG_ALERT_CHANEL_ID }}" >> .env
      

      - name: Send Lighthouse report to Telegram
        run: |
          # Run the script with Node.js
          node --experimental-modules ./send-telegram-report.mjs
